security:
    encoders:
        App\Entity\Utilisateurs:
              algorithm: bcrypt
              cost: 12
        Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12
    providers:
#            my_memory_provider:
#                        memory:
#                            users:
#                                houedraogo:
#                                    password:            $2y$12$a3WFzXhlukdaHJBGD9/.Ou752Xwh0UJN8X/fFAxV9xYdczVgDLeVW #MD5MDP
#                                    roles:               ROLE_USER
#                                asanou:
#                                    password:            $2y$12$mweyBueue5ZdN0oqUUH/Qeb3/eNh65JDl.QPGN4tsaVMghBbvEVma #MD5MDPASANOU
#                                    roles:               [ROLE_USER, ROLE_ADMIN]
            our_db_provider:
                        entity:
                            class: App\Entity\Utilisateurs
                            property: login
    firewalls:
            main:
                provider: our_db_provider
                anonymous: ~
                form_login:
                    login_path: login
                    check_path: login
                    default_target_path: app_main

                logout:       #true
                    path:  logout
                    target:  login


    role_hierarchy:

        #ROLE_GUICHETIER:  ROLE_USER
        ROLE_COMPTABLE: ROLE_GUICHETIER
        ROLE_ADMIN: [ROLE_GUICHETIER, ROLE_COMPTABLE]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_GUICHETIER }