security:

    # encoders pour my_memory_provider..
    encoders:
            App\Entity\Utilisateurs: SHA2

    #encoders:
     #       Symfony\Component\Security\Core\User\User :
      #          algorithm: bcrypt

    providers:
        my_memory_provider:
                    memory:
                        users:
                            houedraogo:
                                password:            MD5MDP
                                roles:               ROLE_USER
                            asanou:
                                password:            MD5MDPASANOU
                                roles:               [ROLE_USER, ROLE_ADMIN]
          #my_db_provider:
           #     entity:
            #        class:               App\Entity\Utilisateurs
             #       #property:            username


    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: check
                username_parameter: login[username]
                password_parameter: login[password]
                default_target_path: /Wrsso
            #provider: my_db_provider
            logout: true
            #logout_path: login

