<?php

namespace App\Repository;

use App\Entity\Billets;
use App\Entity\Devises;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BilletsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BilletsRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Billets::class);
    }

    public function findActive(int $devise){
        if ($devise==0){
            $query = $this->createQueryBuilder('b')
                ->andWhere('b.isActive = true')
                ->andWhere('b.devise is null')
                //->setParameter('statut', true)
                //->setParameter('billet',null)
                ->orderBy('b.valeur', 'DESC')
                ->getQuery()
                ->getResult()
            ;
        }
        else
         $query = $this->createQueryBuilder('b')
            ->andWhere('b.isActive = :statut')
            ->andWhere('b.devise = :devise')
            ->setParameter('statut', true)
            ->setParameter('devise',$devise)
            ->orderBy('b.valeur', 'DESC')
            ->getQuery()
            ->getResult()
            ;
         return $query;
    }
}
