<?php

namespace App\Repository;

use App\Entity\Billets;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BilletsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BilletsRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Billets::class);
    }

    public function findActive(){
        return $this->createQueryBuilder('b')
            ->andWhere('b.isActive = :statut')
            ->setParameter('statut', true)
            ->orderBy('b.valeur', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }
}
