<?php

namespace App\Repository;

use App\Entity\JourneeCaisses;
use Doctrine\ORM\EntityRepository;

/**
 * CaissesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CaissesRepository extends EntityRepository
{
   /* public function getCaissesLibre()

    {
        $co = $this->getEntityManager()->getRepository(JourneeCaisses::class)->getOpenJourneeCaisse();
        //dump($co);die();
        return $this
            ->createQueryBuilder('cl')
            ->where('cl.id in ?co')
            ->setParameter('co', [1,2])
            ->getQuery()
            ->getResult()
            ;
    }
*/

}
