<?php

namespace App\Repository;

use App\Entity\CompenseLignes;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ClientsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */

class CompenseLignesRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CompenseLignes::class);
    }
    
    public function listing(\DateTime $dateDebut, \DateTime $dateFin, $offset=0,$limit = 50)
    {
        return $qb = $this->createQueryBuilder('cl')
            ->select('c.id as cId, c.dateFin as dateFin, SUM(cl.mReceptionAttendu - cl.mEnvoiAttendu) as mAttendu, SUM(cl.mReceptionCompense - cl.mEnvoiCompense) as mCompense')
            ->innerJoin('cl.compense','c', 'WITH', 'cl.compense=c.id')
            ->where('c.dateFin >=?1')->setParameter(1,$dateDebut)
            ->andWhere('c.dateFin<=?2')->setParameter(2, $dateFin)
            ->groupBy('c.id')
            ->orderBy('c.dateFin', 'ASC')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult()
            ;
        //$pag = new Paginator($qb);

        //return $pag;
    }


}
