<?php

namespace App\Repository;

use App\Entity\Compenses;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ClientsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */

class CompensesRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Compenses::class);
    }


    public function liste($offset,$limit = 20)
    {
        $qb = $this->createQueryBuilder('c')
           // ->innerJoin('c.compenseLignes','cl', 'WITH')
            ->orderBy('c.dateDebut', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            //->getQuery()
            //->getResult()
            ;
        $pag = new Paginator($qb);

        return $pag;
    }


}
