<?php

namespace App\Repository;

use App\Entity\Caisses;
use App\Entity\DetteCreditDivers;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * DetteCreditDiversRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DetteCreditDiversRepository extends EntityRepository
{
    public function getTotalDettesCredits(Caisses $caisse){
        $qb = $this->createQueryBuilder('dc');

        try {
            return $qb
                ->select('sum(dc.mDette) as dette,sum(dc.mCredit) as credit ')
                ->where($qb->expr()->eq('dc.caisse', ':caisse'))
                ->andWhere($qb->expr()->orX($qb->expr()->eq('dc.statut', ':credit'), $qb->expr()->eq('dc.statut', ':dette')))
                ->setParameters(['caisse' => $caisse, 'credit' => DetteCreditDivers::CREDIT_EN_COUR, 'dette' => DetteCreditDivers::DETTE_EN_COUR])
                ->getQuery()
                ->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
        }
    }


}
