<?php

namespace App\Repository;

use App\Entity\LigneSalaires;
use App\Entity\Salaires;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * LigneSalaires
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LigneSalairesRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, LigneSalaires::class);
    }

    public function findListingLigneJoinCollabo($salaire){
        return $qb = $this->createQueryBuilder('ls')
            ->addSelect('col')
            ->innerJoin('ls.collaborateur','col')
            ->where('ls.salaire=:salaire')->setParameter('salaire',$salaire)
            ->orderBy('col.nom, col.prenom', 'ASC')
            ->getQuery()->getResult();

    }
}
