<?php

namespace App\Repository;

use App\Entity\Pays;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PaysRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PaysRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Pays::class);
    }

    public function liste($offset=0, $limit = 10)
    {
        $qb=$this->createQueryBuilder('p')
            ->orderBy('p.libelle', 'ASC')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ;
        $pag = new Paginator($qb);

        return $pag;
    }
}
